### ISSUE TITLE
slim-postgres-skeleton

### ISSUE THREAD

**Issue by it-all** [it-all/slim-postgres#38]
Refactor to 2 repos: slim-postgres and slim-postgres-skeleton, similar to the way slim php works. 

- Determine which folders/entities currently under SlimPostgres belong in the skeleton
- Refactor them to be under Domain (most likely)
- Split the repo into 2 - basically just the SlimPostgres folder in slim-postgres and just about everything else in skeleton

**Comment by it-all** [comment]
Done!!!

**Comment by mcsizz** [comment]
Sweet!

Best Regards,

-Tim
